### DISCUSSION TITLE
Couldn't connect to GKE

### DISCUSSION THREAD

**Discussion by fauzislami** [MuhammedKalkan/OpenLens#140] [Q&A]
Hi folks,
first thing first, thanks for making this great tool and I find it useful for sure. I just tried OpenLens as it attracts me to see Kubernetes in a more fascinating view. But there's a little problem when using it, it managed to connect to other clusters except GKE cluster for some reason. Here is what it keeps complaining about:

```
E0414 10:47:38.676509 218787 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable gke-gcloud-auth-plugin not found
Failed to get /version for clusterId=2db3bdb6f00709827a854d8aef738309: Internal Server Error
```

After doing some investigation, I found the kubeconfig for connecting to GKE is a bit different than any regular kubeconfig that I know. It looks as follows: 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE DATA>
    server: https://<IP_ADDRESS>
  name: CLUSTER_NAME
contexts:
- context:
    cluster: CLUSTER_NAME
    namespace: default
    user: CLUSTER_NAME
  name: CLUSTER_NAME
current-context: CLUSTER_NAME
kind: Config
preferences: {}
users:
- name: CLUSTER_NAME
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

have anyone encountered similar issue like this?
